// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("Elders.Proteus")]
[assembly: AssemblyDescriptionAttribute("Elders.Proteus")]
[assembly: AssemblyProductAttribute("Elders.Proteus")]
[assembly: AssemblyVersionAttribute("1.0.6")]
[assembly: AssemblyInformationalVersionAttribute("1.0.6")]
[assembly: AssemblyFileVersionAttribute("1.0.6")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "1.0.6";
    }
}
